[package]
name = "p560_和为K的子数组"
version = "0.1.0"
authors = ["duval <duval1024@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
